services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/project
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username airflow
      --password airflow
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ..:/opt/project
      - C:/Users/godse/.dbt:/home/airflow/.dbt

  airflow-webserver:
    build:
     context: .
     dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/project
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ..:/opt/project
      - C:/Users/godse/.dbt:/home/airflow/.dbt

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/project
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ..:/opt/project
      - C:/Users/godse/.dbt:/home/airflow/.dbt