FROM apache/airflow:2.10.5

USER root

RUN apt-get update && \
    apt-get install -y \
        git \
        openjdk-17-jdk \
        procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow

RUN pip install --no-cache-dir \
    pyspark==3.5.1 \
    delta-spark==3.2.0 \
    dbt-core==1.8.8 \
    dbt-duckdb==1.8.4 \
    great_expectations==0.18.21 \
    google-cloud-bigquery==3.42.2 \
    pyarrow==19.0.0